create table equipment (id uuid not null, date TIMESTAMP WITHOUT TIME ZONE not null, lat float8 not null, lon float8 not null, name varchar(100) not null, equipment_model_id uuid, equipment_id uuid, equipment_state_id uuid, primary key (id));
create table equipment_model (id uuid not null, equipment bytea, name varchar(100) not null, primary key (id));
create table equipment_state (id uuid not null, color varchar(100) not null, value float8 not null, date TIMESTAMP WITHOUT TIME ZONE not null, name varchar(100) not null, equipment_model_id uuid, equipment_state_id uuid, equipment_id uuid, primary key (id));
alter table if exists equipment add constraint FKcuj2jw9cv3p5f9icrqyorc7eb foreign key (equipment_model_id) references equipment_model;
alter table if exists equipment add constraint FKp6xvknr37up2bhg05u2c4qykc foreign key (equipment_id) references equipment;
alter table if exists equipment add constraint FK595heunxd6ekljd3r4qs0qjxa foreign key (equipment_state_id) references equipment_state;
alter table if exists equipment_state add constraint FKgukovmue0c1c8cg8y7akonllm foreign key (equipment_model_id) references equipment_model;
alter table if exists equipment_state add constraint FK7ijbo9xact9yjgxtruvuy43af foreign key (equipment_state_id) references equipment_state;
alter table if exists equipment_state add constraint FKet3gwl38i8y8vtfvvcv2esghq foreign key (equipment_id) references equipment;
create table equipment (id uuid not null, name varchar(100) not null, equipment_model_id uuid, primary key (id));
create table equipment_model (id uuid not null, equipment bytea, name varchar(100) not null, primary key (id));
create table equipment_state (id uuid not null, color varchar(100) not null, value float8 not null, date TIMESTAMP WITHOUT TIME ZONE not null, name varchar(100) not null, equipment_model_id uuid, equipment_state_id uuid, equipment_id uuid, primary key (id));
alter table if exists equipment add constraint FKcuj2jw9cv3p5f9icrqyorc7eb foreign key (equipment_model_id) references equipment_model;
alter table if exists equipment_state add constraint FKgukovmue0c1c8cg8y7akonllm foreign key (equipment_model_id) references equipment_model;
alter table if exists equipment_state add constraint FK7ijbo9xact9yjgxtruvuy43af foreign key (equipment_state_id) references equipment_state;
alter table if exists equipment_state add constraint FKet3gwl38i8y8vtfvvcv2esghq foreign key (equipment_id) references equipment;
create table equipment (id uuid not null, name varchar(100) not null, equipment_model_id uuid, primary key (id));
create table equipment_model (id uuid not null, name varchar(100) not null, primary key (id));
create table equipment_state (id uuid not null, color varchar(100) not null, name varchar(100) not null, primary key (id));
alter table if exists equipment add constraint FKcuj2jw9cv3p5f9icrqyorc7eb foreign key (equipment_model_id) references equipment_model;
create table equipment (id uuid not null, name varchar(100) not null, equipment_model_id uuid, primary key (id));
create table equipment_model (id uuid not null, name varchar(100) not null, primary key (id));
create table equipment_state (id uuid not null, color varchar(100) not null, name varchar(100) not null, primary key (id));
alter table if exists equipment add constraint FKcuj2jw9cv3p5f9icrqyorc7eb foreign key (equipment_model_id) references equipment_model;
create table equipment (id uuid not null, name varchar(100) not null, equipment_model_id uuid, primary key (id));
create table equipment_model (id uuid not null, name varchar(100) not null, primary key (id));
create table equipment_position_history (equipment_id uuid not null, date TIMESTAMP WITHOUT TIME ZONE not null, lat float8 not null, lon float8 not null, primary key (equipment_id));
create table equipment_state (id uuid not null, color varchar(100) not null, name varchar(100) not null, primary key (id));
alter table if exists equipment add constraint FKcuj2jw9cv3p5f9icrqyorc7eb foreign key (equipment_model_id) references equipment_model;
alter table if exists equipment_position_history add constraint FKa49fh2hu80oj5imjrmqfep9yl foreign key (equipment_id) references equipment;
create table equipment (id uuid not null, name varchar(100) not null, equipment_model_id uuid, primary key (id));
create table equipment_model (id uuid not null, name varchar(100) not null, primary key (id));
create table equipment_position_history (equipment_id uuid not null, primary key (equipment_id));
create table equipment_state (id uuid not null, color varchar(100) not null, name varchar(100) not null, primary key (id));
alter table if exists equipment add constraint FKcuj2jw9cv3p5f9icrqyorc7eb foreign key (equipment_model_id) references equipment_model;
alter table if exists equipment_position_history add constraint FKa49fh2hu80oj5imjrmqfep9yl foreign key (equipment_id) references equipment;
