create table operation.equipment (id  serial not null, name varchar(255), equipment_model_id uuid, primary key (id));
create table operation.equipment_model (id  serial not null, name varchar(255), primary key (id));
create table operation.equipment_model_state_hourly_earnings (value float8, equipment_model_id uuid not null, equipment_state_id uuid not null, primary key (equipment_model_id, equipment_state_id));
create table operation.equipment_position_history (date timestamp, lat float8, lon float8, equipment_id uuid not null, primary key (equipment_id));
create table operation.equipment_state (id  serial not null, color varchar(255), name varchar(255), primary key (id));
create table operation.equipment_state_history (date timestamp, equipment_id uuid not null, equipment_state_id uuid, primary key (equipment_id));
alter table operation.equipment add constraint FKcuj2jw9cv3p5f9icrqyorc7eb foreign key (equipment_model_id) references operation.equipment_model;
alter table operation.equipment_model_state_hourly_earnings add constraint FK4qgsqttbi93giw1dv7wpek7rq foreign key (equipment_model_id) references operation.equipment_model;
alter table operation.equipment_model_state_hourly_earnings add constraint FKlvnisfbgnceki5vdcx4007lvf foreign key (equipment_state_id) references operation.equipment_state;
alter table operation.equipment_position_history add constraint FKa49fh2hu80oj5imjrmqfep9yl foreign key (equipment_id) references operation.equipment;
alter table operation.equipment_state_history add constraint FKbjoisje51kuxlm2j8n47qexas foreign key (equipment_id) references operation.equipment;
alter table operation.equipment_state_history add constraint FKw93ox1tgtivyxx9qfwdhx0bd foreign key (equipment_state_id) references operation.equipment_state;
create table operation.equipment (id  serial not null, name varchar(255), equipment_model_id uuid, primary key (id));
create table operation.equipment_model (id  serial not null, name varchar(255), primary key (id));
create table operation.equipment_model_state_hourly_earnings (value float8, equipment_model_id uuid not null, equipment_state_id uuid not null, primary key (equipment_model_id, equipment_state_id));
create table operation.equipment_position_history (date timestamp, lat float8, lon float8, equipment_id uuid not null, primary key (equipment_id));
create table operation.equipment_state (id  serial not null, color varchar(255), name varchar(255), primary key (id));
create table operation.equipment_state_history (date timestamp, equipment_id uuid not null, equipment_state_id uuid, primary key (equipment_id));
alter table operation.equipment add constraint FKcuj2jw9cv3p5f9icrqyorc7eb foreign key (equipment_model_id) references operation.equipment_model;
alter table operation.equipment_model_state_hourly_earnings add constraint FK4qgsqttbi93giw1dv7wpek7rq foreign key (equipment_model_id) references operation.equipment_model;
alter table operation.equipment_model_state_hourly_earnings add constraint FKlvnisfbgnceki5vdcx4007lvf foreign key (equipment_state_id) references operation.equipment_state;
alter table operation.equipment_position_history add constraint FKa49fh2hu80oj5imjrmqfep9yl foreign key (equipment_id) references operation.equipment;
alter table operation.equipment_state_history add constraint FKbjoisje51kuxlm2j8n47qexas foreign key (equipment_id) references operation.equipment;
alter table operation.equipment_state_history add constraint FKw93ox1tgtivyxx9qfwdhx0bd foreign key (equipment_state_id) references operation.equipment_state;
create table operation.equipment (id uuid not null, name varchar(255), equipment_model_id uuid, primary key (id));
create table operation.equipment_model (id  serial not null, name varchar(255), primary key (id));
create table operation.equipment_model_state_hourly_earnings (value float8, equipment_model_id uuid not null, equipment_state_id uuid not null, primary key (equipment_model_id, equipment_state_id));
create table operation.equipment_position_history (date timestamp, lat float8, lon float8, equipment_id uuid not null, primary key (equipment_id));
create table operation.equipment_state (id  serial not null, color varchar(255), name varchar(255), primary key (id));
create table operation.equipment_state_history (date timestamp, equipment_id uuid not null, equipment_state_id uuid, primary key (equipment_id));
alter table if exists operation.equipment add constraint FKcuj2jw9cv3p5f9icrqyorc7eb foreign key (equipment_model_id) references operation.equipment_model;
alter table if exists operation.equipment_model_state_hourly_earnings add constraint FK4qgsqttbi93giw1dv7wpek7rq foreign key (equipment_model_id) references operation.equipment_model;
alter table if exists operation.equipment_model_state_hourly_earnings add constraint FKlvnisfbgnceki5vdcx4007lvf foreign key (equipment_state_id) references operation.equipment_state;
alter table if exists operation.equipment_position_history add constraint FKa49fh2hu80oj5imjrmqfep9yl foreign key (equipment_id) references operation.equipment;
alter table if exists operation.equipment_state_history add constraint FKbjoisje51kuxlm2j8n47qexas foreign key (equipment_id) references operation.equipment;
alter table if exists operation.equipment_state_history add constraint FKw93ox1tgtivyxx9qfwdhx0bd foreign key (equipment_state_id) references operation.equipment_state;
